CREATE TABLE Teacher (
	ID SMALLINT IDENTITY(1,1) NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	DateOfBirth DATE NULL,
	AcademicRank NVARCHAR(50) NOT NULL,
	HireDate DATE NULL,
CONSTRAINT PK_Teacher PRIMARY KEY CLUSTERED 
(
	ID ASC
))
GO