CREATE TABLE Student (
	ID INT IDENTITY(1,1) NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	DateOfBirth DATE NOT NULL,
	EnrolledDate DATETIME NOT NULL,
	Gender CHAR(1) NULL,
	NationalIdNumber BIGINT NOT NULL,
	StudentCardNumber INT NOT NULL
CONSTRAINT PK_Student PRIMARY KEY CLUSTERED 
(
	ID ASC
))
GO