CREATE TABLE Course (
	ID SMALLINT IDENTITY(1,1) NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	Credit INT NOT NULL,
	AcademicYear DATE NOT NULL,
	Semester TINYINT NOT NULL,
CONSTRAINT PK_Course PRIMARY KEY CLUSTERED 
(
	ID ASC
))
GO